name: fargon2
description: A plugin for generating a hash based on Argon2 algorithm in Android / iOS platform.
version: 0.0.1
homepage: https://github.com/iktakahiro/fargon2
repository: https://github.com/iktakahiro/fargon2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.iktakahiro.fargon2
        pluginClass: Fargon2Plugin
      ios:
        pluginClass: Fargon2Plugin
